### ISSUE TITLE
Gloppers does not load on launch

### ISSUE THREAD

**Issue by Ultimushadow** [NotNite/gloppers#1]
Hello, I am having an issue getting Gloppers to load with a modpack I am testing. The behavior I am seeing is that in the Prism logs, Gloppers shows up in the list of mods given to the instance, but does not show up in the list of mods loaded, cannot be viewed in the list of mods in Mod Menu, and does not do anything in game.

Here's the log with the mods I have installed showing the mod missing from the list of loaded mods: (Prism does not alter the log to show that the mod was enabled but I can view it during runtime that the instance has the mod)
[2023-06-26-7.log.gz](https://github.com/NotNite/gloppers/files/11865968/2023-06-26-7.log.gz)

I thought maybe Hopper the Hedgehog or Carpet were preventing Gloppers from loading, but after I disabled them both, it was still missing from the loaded list. If there is another mod I can test to disable, let me know and I'll get back to you asap, thank you

**Comment by NotNite** [comment]
It's possible I've messed up when setting Gloppers to only load on the server and accidentally broke it in singleplayer? I just woke up, so I'll look into this later today.

**Comment by NotNite** [comment]
This should be fixed now in the latest version (1.0.1). Feel free to reopen if you're still having issues!
